git:
    # https://github.com/travis-ci/travis-ci/issues/4575
    depth: 1
env: GHCVER=7.6.3
os: linux
sudo: required
before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - export PATH=$HOME/.ghc-install/$GHCVER/bin:$PATH
 - export PATH=$HOME/bin:$PATH
 - export PATH=$HOME/.cabal/bin:$PATH
 - export PATH=$HOME/.local/bin:$PATH
 - export PATH=/opt/cabal/1.24/bin:$PATH
 - export PATH=/opt/happy/1.19.5/bin:$PATH
 - export PATH=/opt/alex/3.1.7/bin:$PATH
 - ./travis-install.sh
 - mv .cabal $HOME
script:
    - ./travis-test.sh
notifications:
    webhooks:
        urls: https://sake-bot.herokuapp.com/
        on_start: always
  irc:
    channels:
      - "chat.freenode.net##haskell-cabal"
  slack: haskell-cabal:sCq6GLfy9N8MJrInosg871n4
